##################
#General Settings#
##################

## Whether or not to send a message to a player when they vote.
messagePlayer: true

# Whether or not to broadcast to the server when a player votes.
broadcastToServer: true

## If the above is true, should VoteRoulette only broadcast to server the votes from
# online players?
onlyBroadcastOnlinePlayerVotes: false

## If broadcastToServer is set to true, this is the cooldown period (in minutes) before a 
# players votes can be broadcasted to the server again. Useful if you have
# many voting sites and arent using a vote threshold.
broadcastCooldown: 0

## Whether or not to log to the console when a player votes
logToConsole: true

## Whether or not to have the periodic reminder enabled
# You can change this reminder in the messages.yml file.
usePeriodicReminder: true

## How often the periodic reminder is broadcasted (in minutes), if enabled.
periodicReminderInterval: 60

## Whether or not to have players notified when 24 hours have passed since their 
# last vote.
# You can change this reminder in the messages.yml file.
useTwentyFourHourReminder: true

## Whether or not to only consider a players primary group when doing permission group
# checks for Rewards/Milestones
# Setting this to true helps if you are using inheritance in your permission groups.
onlyConsiderPlayersPrimaryGroup: true

## Set this to true to have players unclaimed Rewards/Milestones auto-claimed 
# when they log in.
autoClaimAwards: false

## Disable VoteRoulette from saving unclaimed Rewards/Milestones entirely.
# This means that players voting while offline, and
# players in blacklisted worlds will not get their awards.
# This also means Inventory Protection will be disabled and VoteRoulette will attempt
# to throw the items out from the player when their inventory is full.
disableUnclaimedAwards: false

## Disable VoteRoulettes Inventory Protection and instead have items thrown on the ground
# if a players inventory is full
disableInventoryProtection: false

## Set which command alias you would like to be used
# when VoteRoulette sends text to players.
# You cannot create a new alias with this, please 
# select one of the available options below.
# Options: vr, vtr, voteroulette
defaultCommandAlias: "vr"        

## Set the following to false if you do not want VoteRoulette to automatically check
# for updates. (Anyone with "voteroulette.admin" permission will be notified of an
# update on log in) 
checkForUpdates: true

## Have VoteRoulette print various things its doing to the console.
debug: false

################
# GUI Settings #
################

GUI:
    awards:
        ## Turn on or off the visual representation of rewards/milestone.
        guiForAwards: true
        
        ## If "guiForAwards" is true, this is
        # whether or not to show the commands that will be ran when the player hovers
        # their cursor over the command block
        showCommands: false

        ## If "guiForAwards" is true, this is
        # whether or not to show the eligible players and perm groups for an award
        # when a player hovers their cursor over the details sign
        showPlayersAndGroups: false

    vote-command:
        ## Turn on or off the use of fancy links for the vote command
        # This feature requires MC 1.7 or higher!
        # Fancy links allow you to set placeholder text for links that players can 
        # click on, instead of the link itself.
        # Go to the messages.yml file to see how to create a fancy link.
        useFancyLinks: false

    stats:
        ## Turn on or off the use of the Scoreboard when players issue
        # the /vr top command.
        useScoreboard: true

###################
# Reward Settings #
###################

## Rewards are what are considered for players every time they vote.
# You can set up multiple Rewards and VoteRoulette will pick one at random when a 
# player votes.
#
# Rewards must be created in the awards.yml file. 
# You can also use the in-game Award Creator (Type /vr create)!
#
# Visit the Setup Guide on VoteRoulettes Bukkit page for help with 
# making Rewards and to learn what they can do.

## Set the following to true if you want a Reward to be chosen at random
giveRandomReward: true

## If you set the above to false, specify the Reward name you want VoteRoulette 
# to give for every vote.
defaultReward: Ooh Shiny

## Set the following to true if you only want players to get awarded after they 
# vote so many times
# For example, you want them to vote on all your server lists before getting rewarded
# If this is false, players will receive an award every time they vote
giveRewardsOnThreshold: false

## If the above is set to true, this is the number of how many votes till a player
# will receive a Reward
voteThreshold: 5

## If you set any required worlds for Rewards, the following setting will make
# VoteRoulette consider the Rewards that qualify for the world the player is 
# currently standing in first, and other worlds last.
considerRewardsForPlayersCurrentWorld: true

## The following setting dictates whether or not VoteRoulette will automatically 
# give the player a Reward with vote streak settings when they qualify.
prioritizeVoteStreaks: true


######################
# Milestone Settings #
######################

## Milestones are special rewards that are given after a player has reached so many votes
# They are also created in the awards.yml the same way as Rewards.
# Visit the Setup Guide on VoteRoulettes Bukkit page or use the in-game 
# Award Creator (/vr create) for help with making Milestones!

## Set the following to false if you want players to get a regular Reward on 
# top of a Milestone when they reach a Milestone.
onlyGiveMilestoneUponCompletion: true

## Set the following to true if you have multiple Milestones with the same vote count
# and you want one randomly chosen when a player reaches them.
# If false, the Milestone with the highest priority will be given!   
giveRandomMilestone: false

## If multiple Milestones happen at the same time and some tie for the highest priority,
# the following setting dictates if VoteRoulette will choose a random one 
# or use the first one on the list. This is a good way to mix and match the 
# functionality of random Milestones but still having the control of priorities.
randomizeTiedHighestPriorityMilestones: false

## If you set any required worlds for Milestones, the following setting will make
# VoteRoulette consider the Milestones that qualify for the world the player is 
# currently standing in first, and other worlds last.
considerMilestonesForPlayersCurrentWorld: false

## Turn on or off a random firework that shoots off from the player when they 
# complete a Milestone.
randomFireworkOnMilestone: true

##############
# Blacklists #
##############

## These players will not receive any awards.
blacklistedPlayers:
    - Steve
    - Herobrine

## Set the following to true to switch the above player blacklist to a whitelist, 
# meaning only the players on that list will get awards.
useBlacklistAsWhitelist: false

## Players will not receive Rewards/Milestones in these worlds, ever!
blacklistedWorlds:
    - A_World
    - Another_World

## End of config
##########################################################################################
## No need to touch this
configVersion: 2.0